namespace SimpleCAD
{
    public partial struct FillStyle
    {
		public static FillStyle ActiveBorder { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveBorder)); } }
		public static FillStyle ActiveCaption { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaption)); } }
		public static FillStyle ActiveCaptionText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaptionText)); } }
		public static FillStyle AppWorkspace { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AppWorkspace)); } }
		public static FillStyle Control { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Control)); } }
		public static FillStyle ControlDark { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDark)); } }
		public static FillStyle ControlDarkDark { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDarkDark)); } }
		public static FillStyle ControlLight { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLight)); } }
		public static FillStyle ControlLightLight { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLightLight)); } }
		public static FillStyle ControlText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlText)); } }
		public static FillStyle Desktop { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Desktop)); } }
		public static FillStyle GrayText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GrayText)); } }
		public static FillStyle Highlight { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Highlight)); } }
		public static FillStyle HighlightText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HighlightText)); } }
		public static FillStyle HotTrack { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotTrack)); } }
		public static FillStyle InactiveBorder { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveBorder)); } }
		public static FillStyle InactiveCaption { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaption)); } }
		public static FillStyle InactiveCaptionText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaptionText)); } }
		public static FillStyle Info { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Info)); } }
		public static FillStyle InfoText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InfoText)); } }
		public static FillStyle Menu { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Menu)); } }
		public static FillStyle MenuText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuText)); } }
		public static FillStyle ScrollBar { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ScrollBar)); } }
		public static FillStyle Window { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Window)); } }
		public static FillStyle WindowFrame { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowFrame)); } }
		public static FillStyle WindowText { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowText)); } }
		public static FillStyle Transparent { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Transparent)); } }
		public static FillStyle AliceBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AliceBlue)); } }
		public static FillStyle AntiqueWhite { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AntiqueWhite)); } }
		public static FillStyle Aqua { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aqua)); } }
		public static FillStyle Aquamarine { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aquamarine)); } }
		public static FillStyle Azure { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Azure)); } }
		public static FillStyle Beige { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Beige)); } }
		public static FillStyle Bisque { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Bisque)); } }
		public static FillStyle Black { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Black)); } }
		public static FillStyle BlanchedAlmond { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlanchedAlmond)); } }
		public static FillStyle Blue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Blue)); } }
		public static FillStyle BlueViolet { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlueViolet)); } }
		public static FillStyle Brown { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Brown)); } }
		public static FillStyle BurlyWood { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BurlyWood)); } }
		public static FillStyle CadetBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CadetBlue)); } }
		public static FillStyle Chartreuse { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chartreuse)); } }
		public static FillStyle Chocolate { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chocolate)); } }
		public static FillStyle Coral { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Coral)); } }
		public static FillStyle CornflowerBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CornflowerBlue)); } }
		public static FillStyle Cornsilk { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cornsilk)); } }
		public static FillStyle Crimson { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Crimson)); } }
		public static FillStyle Cyan { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cyan)); } }
		public static FillStyle DarkBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkBlue)); } }
		public static FillStyle DarkCyan { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkCyan)); } }
		public static FillStyle DarkGoldenrod { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGoldenrod)); } }
		public static FillStyle DarkGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGray)); } }
		public static FillStyle DarkGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGreen)); } }
		public static FillStyle DarkKhaki { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkKhaki)); } }
		public static FillStyle DarkMagenta { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkMagenta)); } }
		public static FillStyle DarkOliveGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOliveGreen)); } }
		public static FillStyle DarkOrange { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrange)); } }
		public static FillStyle DarkOrchid { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrchid)); } }
		public static FillStyle DarkRed { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkRed)); } }
		public static FillStyle DarkSalmon { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSalmon)); } }
		public static FillStyle DarkSeaGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSeaGreen)); } }
		public static FillStyle DarkSlateBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateBlue)); } }
		public static FillStyle DarkSlateGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateGray)); } }
		public static FillStyle DarkTurquoise { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkTurquoise)); } }
		public static FillStyle DarkViolet { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkViolet)); } }
		public static FillStyle DeepPink { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepPink)); } }
		public static FillStyle DeepSkyBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepSkyBlue)); } }
		public static FillStyle DimGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DimGray)); } }
		public static FillStyle DodgerBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DodgerBlue)); } }
		public static FillStyle Firebrick { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Firebrick)); } }
		public static FillStyle FloralWhite { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.FloralWhite)); } }
		public static FillStyle ForestGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ForestGreen)); } }
		public static FillStyle Fuchsia { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Fuchsia)); } }
		public static FillStyle Gainsboro { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gainsboro)); } }
		public static FillStyle GhostWhite { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GhostWhite)); } }
		public static FillStyle Gold { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gold)); } }
		public static FillStyle Goldenrod { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Goldenrod)); } }
		public static FillStyle Gray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gray)); } }
		public static FillStyle Green { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Green)); } }
		public static FillStyle GreenYellow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GreenYellow)); } }
		public static FillStyle Honeydew { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Honeydew)); } }
		public static FillStyle HotPink { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotPink)); } }
		public static FillStyle IndianRed { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.IndianRed)); } }
		public static FillStyle Indigo { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Indigo)); } }
		public static FillStyle Ivory { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Ivory)); } }
		public static FillStyle Khaki { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Khaki)); } }
		public static FillStyle Lavender { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lavender)); } }
		public static FillStyle LavenderBlush { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LavenderBlush)); } }
		public static FillStyle LawnGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LawnGreen)); } }
		public static FillStyle LemonChiffon { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LemonChiffon)); } }
		public static FillStyle LightBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightBlue)); } }
		public static FillStyle LightCoral { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCoral)); } }
		public static FillStyle LightCyan { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCyan)); } }
		public static FillStyle LightGoldenrodYellow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGoldenrodYellow)); } }
		public static FillStyle LightGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGray)); } }
		public static FillStyle LightGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGreen)); } }
		public static FillStyle LightPink { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightPink)); } }
		public static FillStyle LightSalmon { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSalmon)); } }
		public static FillStyle LightSeaGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSeaGreen)); } }
		public static FillStyle LightSkyBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSkyBlue)); } }
		public static FillStyle LightSlateGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSlateGray)); } }
		public static FillStyle LightSteelBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSteelBlue)); } }
		public static FillStyle LightYellow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightYellow)); } }
		public static FillStyle Lime { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lime)); } }
		public static FillStyle LimeGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LimeGreen)); } }
		public static FillStyle Linen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Linen)); } }
		public static FillStyle Magenta { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Magenta)); } }
		public static FillStyle Maroon { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Maroon)); } }
		public static FillStyle MediumAquamarine { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumAquamarine)); } }
		public static FillStyle MediumBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumBlue)); } }
		public static FillStyle MediumOrchid { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumOrchid)); } }
		public static FillStyle MediumPurple { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumPurple)); } }
		public static FillStyle MediumSeaGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSeaGreen)); } }
		public static FillStyle MediumSlateBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSlateBlue)); } }
		public static FillStyle MediumSpringGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSpringGreen)); } }
		public static FillStyle MediumTurquoise { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumTurquoise)); } }
		public static FillStyle MediumVioletRed { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumVioletRed)); } }
		public static FillStyle MidnightBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MidnightBlue)); } }
		public static FillStyle MintCream { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MintCream)); } }
		public static FillStyle MistyRose { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MistyRose)); } }
		public static FillStyle Moccasin { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Moccasin)); } }
		public static FillStyle NavajoWhite { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.NavajoWhite)); } }
		public static FillStyle Navy { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Navy)); } }
		public static FillStyle OldLace { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OldLace)); } }
		public static FillStyle Olive { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Olive)); } }
		public static FillStyle OliveDrab { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OliveDrab)); } }
		public static FillStyle Orange { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orange)); } }
		public static FillStyle OrangeRed { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OrangeRed)); } }
		public static FillStyle Orchid { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orchid)); } }
		public static FillStyle PaleGoldenrod { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGoldenrod)); } }
		public static FillStyle PaleGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGreen)); } }
		public static FillStyle PaleTurquoise { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleTurquoise)); } }
		public static FillStyle PaleVioletRed { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleVioletRed)); } }
		public static FillStyle PapayaWhip { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PapayaWhip)); } }
		public static FillStyle PeachPuff { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PeachPuff)); } }
		public static FillStyle Peru { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Peru)); } }
		public static FillStyle Pink { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Pink)); } }
		public static FillStyle Plum { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Plum)); } }
		public static FillStyle PowderBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PowderBlue)); } }
		public static FillStyle Purple { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Purple)); } }
		public static FillStyle Red { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Red)); } }
		public static FillStyle RosyBrown { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RosyBrown)); } }
		public static FillStyle RoyalBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RoyalBlue)); } }
		public static FillStyle SaddleBrown { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SaddleBrown)); } }
		public static FillStyle Salmon { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Salmon)); } }
		public static FillStyle SandyBrown { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SandyBrown)); } }
		public static FillStyle SeaGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaGreen)); } }
		public static FillStyle SeaShell { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaShell)); } }
		public static FillStyle Sienna { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Sienna)); } }
		public static FillStyle Silver { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Silver)); } }
		public static FillStyle SkyBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SkyBlue)); } }
		public static FillStyle SlateBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateBlue)); } }
		public static FillStyle SlateGray { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateGray)); } }
		public static FillStyle Snow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Snow)); } }
		public static FillStyle SpringGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SpringGreen)); } }
		public static FillStyle SteelBlue { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SteelBlue)); } }
		public static FillStyle Tan { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tan)); } }
		public static FillStyle Teal { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Teal)); } }
		public static FillStyle Thistle { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Thistle)); } }
		public static FillStyle Tomato { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tomato)); } }
		public static FillStyle Turquoise { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Turquoise)); } }
		public static FillStyle Violet { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Violet)); } }
		public static FillStyle Wheat { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Wheat)); } }
		public static FillStyle White { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.White)); } }
		public static FillStyle WhiteSmoke { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WhiteSmoke)); } }
		public static FillStyle Yellow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Yellow)); } }
		public static FillStyle YellowGreen { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.YellowGreen)); } }
		public static FillStyle ButtonFace { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonFace)); } }
		public static FillStyle ButtonHighlight { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonHighlight)); } }
		public static FillStyle ButtonShadow { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonShadow)); } }
		public static FillStyle GradientActiveCaption { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientActiveCaption)); } }
		public static FillStyle GradientInactiveCaption { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientInactiveCaption)); } }
		public static FillStyle MenuBar { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuBar)); } }
		public static FillStyle MenuHighlight { get { return new FillStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuHighlight)); } }
	}
}