using System.Drawing;

namespace SimpleCAD
{
    public partial struct FillStyle
    {
		public static FillStyle ActiveBorder { get { return new FillStyle(Color.FromKnownColor(KnownColor.ActiveBorder)); } }
		public static FillStyle ActiveCaption { get { return new FillStyle(Color.FromKnownColor(KnownColor.ActiveCaption)); } }
		public static FillStyle ActiveCaptionText { get { return new FillStyle(Color.FromKnownColor(KnownColor.ActiveCaptionText)); } }
		public static FillStyle AppWorkspace { get { return new FillStyle(Color.FromKnownColor(KnownColor.AppWorkspace)); } }
		public static FillStyle Control { get { return new FillStyle(Color.FromKnownColor(KnownColor.Control)); } }
		public static FillStyle ControlDark { get { return new FillStyle(Color.FromKnownColor(KnownColor.ControlDark)); } }
		public static FillStyle ControlDarkDark { get { return new FillStyle(Color.FromKnownColor(KnownColor.ControlDarkDark)); } }
		public static FillStyle ControlLight { get { return new FillStyle(Color.FromKnownColor(KnownColor.ControlLight)); } }
		public static FillStyle ControlLightLight { get { return new FillStyle(Color.FromKnownColor(KnownColor.ControlLightLight)); } }
		public static FillStyle ControlText { get { return new FillStyle(Color.FromKnownColor(KnownColor.ControlText)); } }
		public static FillStyle Desktop { get { return new FillStyle(Color.FromKnownColor(KnownColor.Desktop)); } }
		public static FillStyle GrayText { get { return new FillStyle(Color.FromKnownColor(KnownColor.GrayText)); } }
		public static FillStyle Highlight { get { return new FillStyle(Color.FromKnownColor(KnownColor.Highlight)); } }
		public static FillStyle HighlightText { get { return new FillStyle(Color.FromKnownColor(KnownColor.HighlightText)); } }
		public static FillStyle HotTrack { get { return new FillStyle(Color.FromKnownColor(KnownColor.HotTrack)); } }
		public static FillStyle InactiveBorder { get { return new FillStyle(Color.FromKnownColor(KnownColor.InactiveBorder)); } }
		public static FillStyle InactiveCaption { get { return new FillStyle(Color.FromKnownColor(KnownColor.InactiveCaption)); } }
		public static FillStyle InactiveCaptionText { get { return new FillStyle(Color.FromKnownColor(KnownColor.InactiveCaptionText)); } }
		public static FillStyle Info { get { return new FillStyle(Color.FromKnownColor(KnownColor.Info)); } }
		public static FillStyle InfoText { get { return new FillStyle(Color.FromKnownColor(KnownColor.InfoText)); } }
		public static FillStyle Menu { get { return new FillStyle(Color.FromKnownColor(KnownColor.Menu)); } }
		public static FillStyle MenuText { get { return new FillStyle(Color.FromKnownColor(KnownColor.MenuText)); } }
		public static FillStyle ScrollBar { get { return new FillStyle(Color.FromKnownColor(KnownColor.ScrollBar)); } }
		public static FillStyle Window { get { return new FillStyle(Color.FromKnownColor(KnownColor.Window)); } }
		public static FillStyle WindowFrame { get { return new FillStyle(Color.FromKnownColor(KnownColor.WindowFrame)); } }
		public static FillStyle WindowText { get { return new FillStyle(Color.FromKnownColor(KnownColor.WindowText)); } }
		public static FillStyle Transparent { get { return new FillStyle(Color.FromKnownColor(KnownColor.Transparent)); } }
		public static FillStyle AliceBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.AliceBlue)); } }
		public static FillStyle AntiqueWhite { get { return new FillStyle(Color.FromKnownColor(KnownColor.AntiqueWhite)); } }
		public static FillStyle Aqua { get { return new FillStyle(Color.FromKnownColor(KnownColor.Aqua)); } }
		public static FillStyle Aquamarine { get { return new FillStyle(Color.FromKnownColor(KnownColor.Aquamarine)); } }
		public static FillStyle Azure { get { return new FillStyle(Color.FromKnownColor(KnownColor.Azure)); } }
		public static FillStyle Beige { get { return new FillStyle(Color.FromKnownColor(KnownColor.Beige)); } }
		public static FillStyle Bisque { get { return new FillStyle(Color.FromKnownColor(KnownColor.Bisque)); } }
		public static FillStyle Black { get { return new FillStyle(Color.FromKnownColor(KnownColor.Black)); } }
		public static FillStyle BlanchedAlmond { get { return new FillStyle(Color.FromKnownColor(KnownColor.BlanchedAlmond)); } }
		public static FillStyle Blue { get { return new FillStyle(Color.FromKnownColor(KnownColor.Blue)); } }
		public static FillStyle BlueViolet { get { return new FillStyle(Color.FromKnownColor(KnownColor.BlueViolet)); } }
		public static FillStyle Brown { get { return new FillStyle(Color.FromKnownColor(KnownColor.Brown)); } }
		public static FillStyle BurlyWood { get { return new FillStyle(Color.FromKnownColor(KnownColor.BurlyWood)); } }
		public static FillStyle CadetBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.CadetBlue)); } }
		public static FillStyle Chartreuse { get { return new FillStyle(Color.FromKnownColor(KnownColor.Chartreuse)); } }
		public static FillStyle Chocolate { get { return new FillStyle(Color.FromKnownColor(KnownColor.Chocolate)); } }
		public static FillStyle Coral { get { return new FillStyle(Color.FromKnownColor(KnownColor.Coral)); } }
		public static FillStyle CornflowerBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.CornflowerBlue)); } }
		public static FillStyle Cornsilk { get { return new FillStyle(Color.FromKnownColor(KnownColor.Cornsilk)); } }
		public static FillStyle Crimson { get { return new FillStyle(Color.FromKnownColor(KnownColor.Crimson)); } }
		public static FillStyle Cyan { get { return new FillStyle(Color.FromKnownColor(KnownColor.Cyan)); } }
		public static FillStyle DarkBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkBlue)); } }
		public static FillStyle DarkCyan { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkCyan)); } }
		public static FillStyle DarkGoldenrod { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkGoldenrod)); } }
		public static FillStyle DarkGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkGray)); } }
		public static FillStyle DarkGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkGreen)); } }
		public static FillStyle DarkKhaki { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkKhaki)); } }
		public static FillStyle DarkMagenta { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkMagenta)); } }
		public static FillStyle DarkOliveGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkOliveGreen)); } }
		public static FillStyle DarkOrange { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkOrange)); } }
		public static FillStyle DarkOrchid { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkOrchid)); } }
		public static FillStyle DarkRed { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkRed)); } }
		public static FillStyle DarkSalmon { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkSalmon)); } }
		public static FillStyle DarkSeaGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkSeaGreen)); } }
		public static FillStyle DarkSlateBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkSlateBlue)); } }
		public static FillStyle DarkSlateGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkSlateGray)); } }
		public static FillStyle DarkTurquoise { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkTurquoise)); } }
		public static FillStyle DarkViolet { get { return new FillStyle(Color.FromKnownColor(KnownColor.DarkViolet)); } }
		public static FillStyle DeepPink { get { return new FillStyle(Color.FromKnownColor(KnownColor.DeepPink)); } }
		public static FillStyle DeepSkyBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.DeepSkyBlue)); } }
		public static FillStyle DimGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.DimGray)); } }
		public static FillStyle DodgerBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.DodgerBlue)); } }
		public static FillStyle Firebrick { get { return new FillStyle(Color.FromKnownColor(KnownColor.Firebrick)); } }
		public static FillStyle FloralWhite { get { return new FillStyle(Color.FromKnownColor(KnownColor.FloralWhite)); } }
		public static FillStyle ForestGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.ForestGreen)); } }
		public static FillStyle Fuchsia { get { return new FillStyle(Color.FromKnownColor(KnownColor.Fuchsia)); } }
		public static FillStyle Gainsboro { get { return new FillStyle(Color.FromKnownColor(KnownColor.Gainsboro)); } }
		public static FillStyle GhostWhite { get { return new FillStyle(Color.FromKnownColor(KnownColor.GhostWhite)); } }
		public static FillStyle Gold { get { return new FillStyle(Color.FromKnownColor(KnownColor.Gold)); } }
		public static FillStyle Goldenrod { get { return new FillStyle(Color.FromKnownColor(KnownColor.Goldenrod)); } }
		public static FillStyle Gray { get { return new FillStyle(Color.FromKnownColor(KnownColor.Gray)); } }
		public static FillStyle Green { get { return new FillStyle(Color.FromKnownColor(KnownColor.Green)); } }
		public static FillStyle GreenYellow { get { return new FillStyle(Color.FromKnownColor(KnownColor.GreenYellow)); } }
		public static FillStyle Honeydew { get { return new FillStyle(Color.FromKnownColor(KnownColor.Honeydew)); } }
		public static FillStyle HotPink { get { return new FillStyle(Color.FromKnownColor(KnownColor.HotPink)); } }
		public static FillStyle IndianRed { get { return new FillStyle(Color.FromKnownColor(KnownColor.IndianRed)); } }
		public static FillStyle Indigo { get { return new FillStyle(Color.FromKnownColor(KnownColor.Indigo)); } }
		public static FillStyle Ivory { get { return new FillStyle(Color.FromKnownColor(KnownColor.Ivory)); } }
		public static FillStyle Khaki { get { return new FillStyle(Color.FromKnownColor(KnownColor.Khaki)); } }
		public static FillStyle Lavender { get { return new FillStyle(Color.FromKnownColor(KnownColor.Lavender)); } }
		public static FillStyle LavenderBlush { get { return new FillStyle(Color.FromKnownColor(KnownColor.LavenderBlush)); } }
		public static FillStyle LawnGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.LawnGreen)); } }
		public static FillStyle LemonChiffon { get { return new FillStyle(Color.FromKnownColor(KnownColor.LemonChiffon)); } }
		public static FillStyle LightBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightBlue)); } }
		public static FillStyle LightCoral { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightCoral)); } }
		public static FillStyle LightCyan { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightCyan)); } }
		public static FillStyle LightGoldenrodYellow { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightGoldenrodYellow)); } }
		public static FillStyle LightGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightGray)); } }
		public static FillStyle LightGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightGreen)); } }
		public static FillStyle LightPink { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightPink)); } }
		public static FillStyle LightSalmon { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightSalmon)); } }
		public static FillStyle LightSeaGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightSeaGreen)); } }
		public static FillStyle LightSkyBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightSkyBlue)); } }
		public static FillStyle LightSlateGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightSlateGray)); } }
		public static FillStyle LightSteelBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightSteelBlue)); } }
		public static FillStyle LightYellow { get { return new FillStyle(Color.FromKnownColor(KnownColor.LightYellow)); } }
		public static FillStyle Lime { get { return new FillStyle(Color.FromKnownColor(KnownColor.Lime)); } }
		public static FillStyle LimeGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.LimeGreen)); } }
		public static FillStyle Linen { get { return new FillStyle(Color.FromKnownColor(KnownColor.Linen)); } }
		public static FillStyle Magenta { get { return new FillStyle(Color.FromKnownColor(KnownColor.Magenta)); } }
		public static FillStyle Maroon { get { return new FillStyle(Color.FromKnownColor(KnownColor.Maroon)); } }
		public static FillStyle MediumAquamarine { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumAquamarine)); } }
		public static FillStyle MediumBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumBlue)); } }
		public static FillStyle MediumOrchid { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumOrchid)); } }
		public static FillStyle MediumPurple { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumPurple)); } }
		public static FillStyle MediumSeaGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumSeaGreen)); } }
		public static FillStyle MediumSlateBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumSlateBlue)); } }
		public static FillStyle MediumSpringGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumSpringGreen)); } }
		public static FillStyle MediumTurquoise { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumTurquoise)); } }
		public static FillStyle MediumVioletRed { get { return new FillStyle(Color.FromKnownColor(KnownColor.MediumVioletRed)); } }
		public static FillStyle MidnightBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.MidnightBlue)); } }
		public static FillStyle MintCream { get { return new FillStyle(Color.FromKnownColor(KnownColor.MintCream)); } }
		public static FillStyle MistyRose { get { return new FillStyle(Color.FromKnownColor(KnownColor.MistyRose)); } }
		public static FillStyle Moccasin { get { return new FillStyle(Color.FromKnownColor(KnownColor.Moccasin)); } }
		public static FillStyle NavajoWhite { get { return new FillStyle(Color.FromKnownColor(KnownColor.NavajoWhite)); } }
		public static FillStyle Navy { get { return new FillStyle(Color.FromKnownColor(KnownColor.Navy)); } }
		public static FillStyle OldLace { get { return new FillStyle(Color.FromKnownColor(KnownColor.OldLace)); } }
		public static FillStyle Olive { get { return new FillStyle(Color.FromKnownColor(KnownColor.Olive)); } }
		public static FillStyle OliveDrab { get { return new FillStyle(Color.FromKnownColor(KnownColor.OliveDrab)); } }
		public static FillStyle Orange { get { return new FillStyle(Color.FromKnownColor(KnownColor.Orange)); } }
		public static FillStyle OrangeRed { get { return new FillStyle(Color.FromKnownColor(KnownColor.OrangeRed)); } }
		public static FillStyle Orchid { get { return new FillStyle(Color.FromKnownColor(KnownColor.Orchid)); } }
		public static FillStyle PaleGoldenrod { get { return new FillStyle(Color.FromKnownColor(KnownColor.PaleGoldenrod)); } }
		public static FillStyle PaleGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.PaleGreen)); } }
		public static FillStyle PaleTurquoise { get { return new FillStyle(Color.FromKnownColor(KnownColor.PaleTurquoise)); } }
		public static FillStyle PaleVioletRed { get { return new FillStyle(Color.FromKnownColor(KnownColor.PaleVioletRed)); } }
		public static FillStyle PapayaWhip { get { return new FillStyle(Color.FromKnownColor(KnownColor.PapayaWhip)); } }
		public static FillStyle PeachPuff { get { return new FillStyle(Color.FromKnownColor(KnownColor.PeachPuff)); } }
		public static FillStyle Peru { get { return new FillStyle(Color.FromKnownColor(KnownColor.Peru)); } }
		public static FillStyle Pink { get { return new FillStyle(Color.FromKnownColor(KnownColor.Pink)); } }
		public static FillStyle Plum { get { return new FillStyle(Color.FromKnownColor(KnownColor.Plum)); } }
		public static FillStyle PowderBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.PowderBlue)); } }
		public static FillStyle Purple { get { return new FillStyle(Color.FromKnownColor(KnownColor.Purple)); } }
		public static FillStyle Red { get { return new FillStyle(Color.FromKnownColor(KnownColor.Red)); } }
		public static FillStyle RosyBrown { get { return new FillStyle(Color.FromKnownColor(KnownColor.RosyBrown)); } }
		public static FillStyle RoyalBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.RoyalBlue)); } }
		public static FillStyle SaddleBrown { get { return new FillStyle(Color.FromKnownColor(KnownColor.SaddleBrown)); } }
		public static FillStyle Salmon { get { return new FillStyle(Color.FromKnownColor(KnownColor.Salmon)); } }
		public static FillStyle SandyBrown { get { return new FillStyle(Color.FromKnownColor(KnownColor.SandyBrown)); } }
		public static FillStyle SeaGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.SeaGreen)); } }
		public static FillStyle SeaShell { get { return new FillStyle(Color.FromKnownColor(KnownColor.SeaShell)); } }
		public static FillStyle Sienna { get { return new FillStyle(Color.FromKnownColor(KnownColor.Sienna)); } }
		public static FillStyle Silver { get { return new FillStyle(Color.FromKnownColor(KnownColor.Silver)); } }
		public static FillStyle SkyBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.SkyBlue)); } }
		public static FillStyle SlateBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.SlateBlue)); } }
		public static FillStyle SlateGray { get { return new FillStyle(Color.FromKnownColor(KnownColor.SlateGray)); } }
		public static FillStyle Snow { get { return new FillStyle(Color.FromKnownColor(KnownColor.Snow)); } }
		public static FillStyle SpringGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.SpringGreen)); } }
		public static FillStyle SteelBlue { get { return new FillStyle(Color.FromKnownColor(KnownColor.SteelBlue)); } }
		public static FillStyle Tan { get { return new FillStyle(Color.FromKnownColor(KnownColor.Tan)); } }
		public static FillStyle Teal { get { return new FillStyle(Color.FromKnownColor(KnownColor.Teal)); } }
		public static FillStyle Thistle { get { return new FillStyle(Color.FromKnownColor(KnownColor.Thistle)); } }
		public static FillStyle Tomato { get { return new FillStyle(Color.FromKnownColor(KnownColor.Tomato)); } }
		public static FillStyle Turquoise { get { return new FillStyle(Color.FromKnownColor(KnownColor.Turquoise)); } }
		public static FillStyle Violet { get { return new FillStyle(Color.FromKnownColor(KnownColor.Violet)); } }
		public static FillStyle Wheat { get { return new FillStyle(Color.FromKnownColor(KnownColor.Wheat)); } }
		public static FillStyle White { get { return new FillStyle(Color.FromKnownColor(KnownColor.White)); } }
		public static FillStyle WhiteSmoke { get { return new FillStyle(Color.FromKnownColor(KnownColor.WhiteSmoke)); } }
		public static FillStyle Yellow { get { return new FillStyle(Color.FromKnownColor(KnownColor.Yellow)); } }
		public static FillStyle YellowGreen { get { return new FillStyle(Color.FromKnownColor(KnownColor.YellowGreen)); } }
		public static FillStyle ButtonFace { get { return new FillStyle(Color.FromKnownColor(KnownColor.ButtonFace)); } }
		public static FillStyle ButtonHighlight { get { return new FillStyle(Color.FromKnownColor(KnownColor.ButtonHighlight)); } }
		public static FillStyle ButtonShadow { get { return new FillStyle(Color.FromKnownColor(KnownColor.ButtonShadow)); } }
		public static FillStyle GradientActiveCaption { get { return new FillStyle(Color.FromKnownColor(KnownColor.GradientActiveCaption)); } }
		public static FillStyle GradientInactiveCaption { get { return new FillStyle(Color.FromKnownColor(KnownColor.GradientInactiveCaption)); } }
		public static FillStyle MenuBar { get { return new FillStyle(Color.FromKnownColor(KnownColor.MenuBar)); } }
		public static FillStyle MenuHighlight { get { return new FillStyle(Color.FromKnownColor(KnownColor.MenuHighlight)); } }
	}
}