using System.Drawing;

namespace SimpleCAD
{
    public partial struct OutlineStyle
    {
		public static OutlineStyle ActiveBorder { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ActiveBorder)); } }
		public static OutlineStyle ActiveCaption { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ActiveCaption)); } }
		public static OutlineStyle ActiveCaptionText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ActiveCaptionText)); } }
		public static OutlineStyle AppWorkspace { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.AppWorkspace)); } }
		public static OutlineStyle Control { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Control)); } }
		public static OutlineStyle ControlDark { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ControlDark)); } }
		public static OutlineStyle ControlDarkDark { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ControlDarkDark)); } }
		public static OutlineStyle ControlLight { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ControlLight)); } }
		public static OutlineStyle ControlLightLight { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ControlLightLight)); } }
		public static OutlineStyle ControlText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ControlText)); } }
		public static OutlineStyle Desktop { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Desktop)); } }
		public static OutlineStyle GrayText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.GrayText)); } }
		public static OutlineStyle Highlight { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Highlight)); } }
		public static OutlineStyle HighlightText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.HighlightText)); } }
		public static OutlineStyle HotTrack { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.HotTrack)); } }
		public static OutlineStyle InactiveBorder { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.InactiveBorder)); } }
		public static OutlineStyle InactiveCaption { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.InactiveCaption)); } }
		public static OutlineStyle InactiveCaptionText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.InactiveCaptionText)); } }
		public static OutlineStyle Info { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Info)); } }
		public static OutlineStyle InfoText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.InfoText)); } }
		public static OutlineStyle Menu { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Menu)); } }
		public static OutlineStyle MenuText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MenuText)); } }
		public static OutlineStyle ScrollBar { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ScrollBar)); } }
		public static OutlineStyle Window { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Window)); } }
		public static OutlineStyle WindowFrame { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.WindowFrame)); } }
		public static OutlineStyle WindowText { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.WindowText)); } }
		public static OutlineStyle Transparent { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Transparent)); } }
		public static OutlineStyle AliceBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.AliceBlue)); } }
		public static OutlineStyle AntiqueWhite { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.AntiqueWhite)); } }
		public static OutlineStyle Aqua { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Aqua)); } }
		public static OutlineStyle Aquamarine { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Aquamarine)); } }
		public static OutlineStyle Azure { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Azure)); } }
		public static OutlineStyle Beige { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Beige)); } }
		public static OutlineStyle Bisque { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Bisque)); } }
		public static OutlineStyle Black { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Black)); } }
		public static OutlineStyle BlanchedAlmond { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.BlanchedAlmond)); } }
		public static OutlineStyle Blue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Blue)); } }
		public static OutlineStyle BlueViolet { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.BlueViolet)); } }
		public static OutlineStyle Brown { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Brown)); } }
		public static OutlineStyle BurlyWood { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.BurlyWood)); } }
		public static OutlineStyle CadetBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.CadetBlue)); } }
		public static OutlineStyle Chartreuse { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Chartreuse)); } }
		public static OutlineStyle Chocolate { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Chocolate)); } }
		public static OutlineStyle Coral { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Coral)); } }
		public static OutlineStyle CornflowerBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.CornflowerBlue)); } }
		public static OutlineStyle Cornsilk { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Cornsilk)); } }
		public static OutlineStyle Crimson { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Crimson)); } }
		public static OutlineStyle Cyan { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Cyan)); } }
		public static OutlineStyle DarkBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkBlue)); } }
		public static OutlineStyle DarkCyan { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkCyan)); } }
		public static OutlineStyle DarkGoldenrod { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkGoldenrod)); } }
		public static OutlineStyle DarkGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkGray)); } }
		public static OutlineStyle DarkGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkGreen)); } }
		public static OutlineStyle DarkKhaki { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkKhaki)); } }
		public static OutlineStyle DarkMagenta { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkMagenta)); } }
		public static OutlineStyle DarkOliveGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkOliveGreen)); } }
		public static OutlineStyle DarkOrange { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkOrange)); } }
		public static OutlineStyle DarkOrchid { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkOrchid)); } }
		public static OutlineStyle DarkRed { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkRed)); } }
		public static OutlineStyle DarkSalmon { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkSalmon)); } }
		public static OutlineStyle DarkSeaGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkSeaGreen)); } }
		public static OutlineStyle DarkSlateBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkSlateBlue)); } }
		public static OutlineStyle DarkSlateGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkSlateGray)); } }
		public static OutlineStyle DarkTurquoise { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkTurquoise)); } }
		public static OutlineStyle DarkViolet { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DarkViolet)); } }
		public static OutlineStyle DeepPink { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DeepPink)); } }
		public static OutlineStyle DeepSkyBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DeepSkyBlue)); } }
		public static OutlineStyle DimGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DimGray)); } }
		public static OutlineStyle DodgerBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.DodgerBlue)); } }
		public static OutlineStyle Firebrick { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Firebrick)); } }
		public static OutlineStyle FloralWhite { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.FloralWhite)); } }
		public static OutlineStyle ForestGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ForestGreen)); } }
		public static OutlineStyle Fuchsia { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Fuchsia)); } }
		public static OutlineStyle Gainsboro { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Gainsboro)); } }
		public static OutlineStyle GhostWhite { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.GhostWhite)); } }
		public static OutlineStyle Gold { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Gold)); } }
		public static OutlineStyle Goldenrod { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Goldenrod)); } }
		public static OutlineStyle Gray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Gray)); } }
		public static OutlineStyle Green { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Green)); } }
		public static OutlineStyle GreenYellow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.GreenYellow)); } }
		public static OutlineStyle Honeydew { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Honeydew)); } }
		public static OutlineStyle HotPink { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.HotPink)); } }
		public static OutlineStyle IndianRed { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.IndianRed)); } }
		public static OutlineStyle Indigo { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Indigo)); } }
		public static OutlineStyle Ivory { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Ivory)); } }
		public static OutlineStyle Khaki { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Khaki)); } }
		public static OutlineStyle Lavender { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Lavender)); } }
		public static OutlineStyle LavenderBlush { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LavenderBlush)); } }
		public static OutlineStyle LawnGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LawnGreen)); } }
		public static OutlineStyle LemonChiffon { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LemonChiffon)); } }
		public static OutlineStyle LightBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightBlue)); } }
		public static OutlineStyle LightCoral { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightCoral)); } }
		public static OutlineStyle LightCyan { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightCyan)); } }
		public static OutlineStyle LightGoldenrodYellow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightGoldenrodYellow)); } }
		public static OutlineStyle LightGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightGray)); } }
		public static OutlineStyle LightGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightGreen)); } }
		public static OutlineStyle LightPink { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightPink)); } }
		public static OutlineStyle LightSalmon { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightSalmon)); } }
		public static OutlineStyle LightSeaGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightSeaGreen)); } }
		public static OutlineStyle LightSkyBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightSkyBlue)); } }
		public static OutlineStyle LightSlateGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightSlateGray)); } }
		public static OutlineStyle LightSteelBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightSteelBlue)); } }
		public static OutlineStyle LightYellow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LightYellow)); } }
		public static OutlineStyle Lime { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Lime)); } }
		public static OutlineStyle LimeGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.LimeGreen)); } }
		public static OutlineStyle Linen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Linen)); } }
		public static OutlineStyle Magenta { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Magenta)); } }
		public static OutlineStyle Maroon { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Maroon)); } }
		public static OutlineStyle MediumAquamarine { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumAquamarine)); } }
		public static OutlineStyle MediumBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumBlue)); } }
		public static OutlineStyle MediumOrchid { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumOrchid)); } }
		public static OutlineStyle MediumPurple { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumPurple)); } }
		public static OutlineStyle MediumSeaGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumSeaGreen)); } }
		public static OutlineStyle MediumSlateBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumSlateBlue)); } }
		public static OutlineStyle MediumSpringGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumSpringGreen)); } }
		public static OutlineStyle MediumTurquoise { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumTurquoise)); } }
		public static OutlineStyle MediumVioletRed { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MediumVioletRed)); } }
		public static OutlineStyle MidnightBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MidnightBlue)); } }
		public static OutlineStyle MintCream { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MintCream)); } }
		public static OutlineStyle MistyRose { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MistyRose)); } }
		public static OutlineStyle Moccasin { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Moccasin)); } }
		public static OutlineStyle NavajoWhite { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.NavajoWhite)); } }
		public static OutlineStyle Navy { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Navy)); } }
		public static OutlineStyle OldLace { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.OldLace)); } }
		public static OutlineStyle Olive { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Olive)); } }
		public static OutlineStyle OliveDrab { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.OliveDrab)); } }
		public static OutlineStyle Orange { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Orange)); } }
		public static OutlineStyle OrangeRed { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.OrangeRed)); } }
		public static OutlineStyle Orchid { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Orchid)); } }
		public static OutlineStyle PaleGoldenrod { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PaleGoldenrod)); } }
		public static OutlineStyle PaleGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PaleGreen)); } }
		public static OutlineStyle PaleTurquoise { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PaleTurquoise)); } }
		public static OutlineStyle PaleVioletRed { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PaleVioletRed)); } }
		public static OutlineStyle PapayaWhip { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PapayaWhip)); } }
		public static OutlineStyle PeachPuff { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PeachPuff)); } }
		public static OutlineStyle Peru { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Peru)); } }
		public static OutlineStyle Pink { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Pink)); } }
		public static OutlineStyle Plum { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Plum)); } }
		public static OutlineStyle PowderBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.PowderBlue)); } }
		public static OutlineStyle Purple { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Purple)); } }
		public static OutlineStyle Red { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Red)); } }
		public static OutlineStyle RosyBrown { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.RosyBrown)); } }
		public static OutlineStyle RoyalBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.RoyalBlue)); } }
		public static OutlineStyle SaddleBrown { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SaddleBrown)); } }
		public static OutlineStyle Salmon { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Salmon)); } }
		public static OutlineStyle SandyBrown { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SandyBrown)); } }
		public static OutlineStyle SeaGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SeaGreen)); } }
		public static OutlineStyle SeaShell { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SeaShell)); } }
		public static OutlineStyle Sienna { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Sienna)); } }
		public static OutlineStyle Silver { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Silver)); } }
		public static OutlineStyle SkyBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SkyBlue)); } }
		public static OutlineStyle SlateBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SlateBlue)); } }
		public static OutlineStyle SlateGray { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SlateGray)); } }
		public static OutlineStyle Snow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Snow)); } }
		public static OutlineStyle SpringGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SpringGreen)); } }
		public static OutlineStyle SteelBlue { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.SteelBlue)); } }
		public static OutlineStyle Tan { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Tan)); } }
		public static OutlineStyle Teal { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Teal)); } }
		public static OutlineStyle Thistle { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Thistle)); } }
		public static OutlineStyle Tomato { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Tomato)); } }
		public static OutlineStyle Turquoise { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Turquoise)); } }
		public static OutlineStyle Violet { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Violet)); } }
		public static OutlineStyle Wheat { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Wheat)); } }
		public static OutlineStyle White { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.White)); } }
		public static OutlineStyle WhiteSmoke { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.WhiteSmoke)); } }
		public static OutlineStyle Yellow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.Yellow)); } }
		public static OutlineStyle YellowGreen { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.YellowGreen)); } }
		public static OutlineStyle ButtonFace { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ButtonFace)); } }
		public static OutlineStyle ButtonHighlight { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ButtonHighlight)); } }
		public static OutlineStyle ButtonShadow { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.ButtonShadow)); } }
		public static OutlineStyle GradientActiveCaption { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.GradientActiveCaption)); } }
		public static OutlineStyle GradientInactiveCaption { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.GradientInactiveCaption)); } }
		public static OutlineStyle MenuBar { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MenuBar)); } }
		public static OutlineStyle MenuHighlight { get { return new OutlineStyle(Color.FromKnownColor(KnownColor.MenuHighlight)); } }
	}
}