namespace SimpleCAD
{
    public partial struct Outline
    {
		public static Outline ActiveBorder { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveBorder)); } }
		public static Outline ActiveCaption { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaption)); } }
		public static Outline ActiveCaptionText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaptionText)); } }
		public static Outline AppWorkspace { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AppWorkspace)); } }
		public static Outline Control { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Control)); } }
		public static Outline ControlDark { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDark)); } }
		public static Outline ControlDarkDark { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDarkDark)); } }
		public static Outline ControlLight { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLight)); } }
		public static Outline ControlLightLight { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLightLight)); } }
		public static Outline ControlText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlText)); } }
		public static Outline Desktop { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Desktop)); } }
		public static Outline GrayText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GrayText)); } }
		public static Outline Highlight { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Highlight)); } }
		public static Outline HighlightText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HighlightText)); } }
		public static Outline HotTrack { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotTrack)); } }
		public static Outline InactiveBorder { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveBorder)); } }
		public static Outline InactiveCaption { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaption)); } }
		public static Outline InactiveCaptionText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaptionText)); } }
		public static Outline Info { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Info)); } }
		public static Outline InfoText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InfoText)); } }
		public static Outline Menu { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Menu)); } }
		public static Outline MenuText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuText)); } }
		public static Outline ScrollBar { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ScrollBar)); } }
		public static Outline Window { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Window)); } }
		public static Outline WindowFrame { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowFrame)); } }
		public static Outline WindowText { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowText)); } }
		public static Outline Transparent { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Transparent)); } }
		public static Outline AliceBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AliceBlue)); } }
		public static Outline AntiqueWhite { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AntiqueWhite)); } }
		public static Outline Aqua { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aqua)); } }
		public static Outline Aquamarine { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aquamarine)); } }
		public static Outline Azure { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Azure)); } }
		public static Outline Beige { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Beige)); } }
		public static Outline Bisque { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Bisque)); } }
		public static Outline Black { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Black)); } }
		public static Outline BlanchedAlmond { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlanchedAlmond)); } }
		public static Outline Blue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Blue)); } }
		public static Outline BlueViolet { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlueViolet)); } }
		public static Outline Brown { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Brown)); } }
		public static Outline BurlyWood { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BurlyWood)); } }
		public static Outline CadetBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CadetBlue)); } }
		public static Outline Chartreuse { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chartreuse)); } }
		public static Outline Chocolate { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chocolate)); } }
		public static Outline Coral { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Coral)); } }
		public static Outline CornflowerBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CornflowerBlue)); } }
		public static Outline Cornsilk { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cornsilk)); } }
		public static Outline Crimson { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Crimson)); } }
		public static Outline Cyan { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cyan)); } }
		public static Outline DarkBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkBlue)); } }
		public static Outline DarkCyan { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkCyan)); } }
		public static Outline DarkGoldenrod { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGoldenrod)); } }
		public static Outline DarkGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGray)); } }
		public static Outline DarkGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGreen)); } }
		public static Outline DarkKhaki { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkKhaki)); } }
		public static Outline DarkMagenta { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkMagenta)); } }
		public static Outline DarkOliveGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOliveGreen)); } }
		public static Outline DarkOrange { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrange)); } }
		public static Outline DarkOrchid { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrchid)); } }
		public static Outline DarkRed { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkRed)); } }
		public static Outline DarkSalmon { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSalmon)); } }
		public static Outline DarkSeaGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSeaGreen)); } }
		public static Outline DarkSlateBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateBlue)); } }
		public static Outline DarkSlateGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateGray)); } }
		public static Outline DarkTurquoise { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkTurquoise)); } }
		public static Outline DarkViolet { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkViolet)); } }
		public static Outline DeepPink { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepPink)); } }
		public static Outline DeepSkyBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepSkyBlue)); } }
		public static Outline DimGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DimGray)); } }
		public static Outline DodgerBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DodgerBlue)); } }
		public static Outline Firebrick { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Firebrick)); } }
		public static Outline FloralWhite { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.FloralWhite)); } }
		public static Outline ForestGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ForestGreen)); } }
		public static Outline Fuchsia { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Fuchsia)); } }
		public static Outline Gainsboro { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gainsboro)); } }
		public static Outline GhostWhite { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GhostWhite)); } }
		public static Outline Gold { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gold)); } }
		public static Outline Goldenrod { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Goldenrod)); } }
		public static Outline Gray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gray)); } }
		public static Outline Green { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Green)); } }
		public static Outline GreenYellow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GreenYellow)); } }
		public static Outline Honeydew { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Honeydew)); } }
		public static Outline HotPink { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotPink)); } }
		public static Outline IndianRed { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.IndianRed)); } }
		public static Outline Indigo { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Indigo)); } }
		public static Outline Ivory { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Ivory)); } }
		public static Outline Khaki { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Khaki)); } }
		public static Outline Lavender { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lavender)); } }
		public static Outline LavenderBlush { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LavenderBlush)); } }
		public static Outline LawnGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LawnGreen)); } }
		public static Outline LemonChiffon { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LemonChiffon)); } }
		public static Outline LightBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightBlue)); } }
		public static Outline LightCoral { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCoral)); } }
		public static Outline LightCyan { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCyan)); } }
		public static Outline LightGoldenrodYellow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGoldenrodYellow)); } }
		public static Outline LightGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGray)); } }
		public static Outline LightGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGreen)); } }
		public static Outline LightPink { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightPink)); } }
		public static Outline LightSalmon { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSalmon)); } }
		public static Outline LightSeaGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSeaGreen)); } }
		public static Outline LightSkyBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSkyBlue)); } }
		public static Outline LightSlateGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSlateGray)); } }
		public static Outline LightSteelBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSteelBlue)); } }
		public static Outline LightYellow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightYellow)); } }
		public static Outline Lime { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lime)); } }
		public static Outline LimeGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LimeGreen)); } }
		public static Outline Linen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Linen)); } }
		public static Outline Magenta { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Magenta)); } }
		public static Outline Maroon { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Maroon)); } }
		public static Outline MediumAquamarine { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumAquamarine)); } }
		public static Outline MediumBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumBlue)); } }
		public static Outline MediumOrchid { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumOrchid)); } }
		public static Outline MediumPurple { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumPurple)); } }
		public static Outline MediumSeaGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSeaGreen)); } }
		public static Outline MediumSlateBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSlateBlue)); } }
		public static Outline MediumSpringGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSpringGreen)); } }
		public static Outline MediumTurquoise { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumTurquoise)); } }
		public static Outline MediumVioletRed { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumVioletRed)); } }
		public static Outline MidnightBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MidnightBlue)); } }
		public static Outline MintCream { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MintCream)); } }
		public static Outline MistyRose { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MistyRose)); } }
		public static Outline Moccasin { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Moccasin)); } }
		public static Outline NavajoWhite { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.NavajoWhite)); } }
		public static Outline Navy { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Navy)); } }
		public static Outline OldLace { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OldLace)); } }
		public static Outline Olive { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Olive)); } }
		public static Outline OliveDrab { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OliveDrab)); } }
		public static Outline Orange { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orange)); } }
		public static Outline OrangeRed { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OrangeRed)); } }
		public static Outline Orchid { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orchid)); } }
		public static Outline PaleGoldenrod { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGoldenrod)); } }
		public static Outline PaleGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGreen)); } }
		public static Outline PaleTurquoise { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleTurquoise)); } }
		public static Outline PaleVioletRed { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleVioletRed)); } }
		public static Outline PapayaWhip { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PapayaWhip)); } }
		public static Outline PeachPuff { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PeachPuff)); } }
		public static Outline Peru { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Peru)); } }
		public static Outline Pink { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Pink)); } }
		public static Outline Plum { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Plum)); } }
		public static Outline PowderBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PowderBlue)); } }
		public static Outline Purple { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Purple)); } }
		public static Outline Red { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Red)); } }
		public static Outline RosyBrown { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RosyBrown)); } }
		public static Outline RoyalBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RoyalBlue)); } }
		public static Outline SaddleBrown { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SaddleBrown)); } }
		public static Outline Salmon { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Salmon)); } }
		public static Outline SandyBrown { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SandyBrown)); } }
		public static Outline SeaGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaGreen)); } }
		public static Outline SeaShell { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaShell)); } }
		public static Outline Sienna { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Sienna)); } }
		public static Outline Silver { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Silver)); } }
		public static Outline SkyBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SkyBlue)); } }
		public static Outline SlateBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateBlue)); } }
		public static Outline SlateGray { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateGray)); } }
		public static Outline Snow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Snow)); } }
		public static Outline SpringGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SpringGreen)); } }
		public static Outline SteelBlue { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SteelBlue)); } }
		public static Outline Tan { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tan)); } }
		public static Outline Teal { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Teal)); } }
		public static Outline Thistle { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Thistle)); } }
		public static Outline Tomato { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tomato)); } }
		public static Outline Turquoise { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Turquoise)); } }
		public static Outline Violet { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Violet)); } }
		public static Outline Wheat { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Wheat)); } }
		public static Outline White { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.White)); } }
		public static Outline WhiteSmoke { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WhiteSmoke)); } }
		public static Outline Yellow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Yellow)); } }
		public static Outline YellowGreen { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.YellowGreen)); } }
		public static Outline ButtonFace { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonFace)); } }
		public static Outline ButtonHighlight { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonHighlight)); } }
		public static Outline ButtonShadow { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonShadow)); } }
		public static Outline GradientActiveCaption { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientActiveCaption)); } }
		public static Outline GradientInactiveCaption { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientInactiveCaption)); } }
		public static Outline MenuBar { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuBar)); } }
		public static Outline MenuHighlight { get { return new Outline(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuHighlight)); } }
	}
}