namespace SimpleCAD
{
    public partial struct OutlineStyle
    {
		public static OutlineStyle ActiveBorder { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveBorder)); } }
		public static OutlineStyle ActiveCaption { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaption)); } }
		public static OutlineStyle ActiveCaptionText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaptionText)); } }
		public static OutlineStyle AppWorkspace { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AppWorkspace)); } }
		public static OutlineStyle Control { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Control)); } }
		public static OutlineStyle ControlDark { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDark)); } }
		public static OutlineStyle ControlDarkDark { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDarkDark)); } }
		public static OutlineStyle ControlLight { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLight)); } }
		public static OutlineStyle ControlLightLight { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLightLight)); } }
		public static OutlineStyle ControlText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlText)); } }
		public static OutlineStyle Desktop { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Desktop)); } }
		public static OutlineStyle GrayText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GrayText)); } }
		public static OutlineStyle Highlight { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Highlight)); } }
		public static OutlineStyle HighlightText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HighlightText)); } }
		public static OutlineStyle HotTrack { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotTrack)); } }
		public static OutlineStyle InactiveBorder { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveBorder)); } }
		public static OutlineStyle InactiveCaption { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaption)); } }
		public static OutlineStyle InactiveCaptionText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaptionText)); } }
		public static OutlineStyle Info { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Info)); } }
		public static OutlineStyle InfoText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InfoText)); } }
		public static OutlineStyle Menu { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Menu)); } }
		public static OutlineStyle MenuText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuText)); } }
		public static OutlineStyle ScrollBar { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ScrollBar)); } }
		public static OutlineStyle Window { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Window)); } }
		public static OutlineStyle WindowFrame { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowFrame)); } }
		public static OutlineStyle WindowText { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowText)); } }
		public static OutlineStyle Transparent { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Transparent)); } }
		public static OutlineStyle AliceBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AliceBlue)); } }
		public static OutlineStyle AntiqueWhite { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AntiqueWhite)); } }
		public static OutlineStyle Aqua { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aqua)); } }
		public static OutlineStyle Aquamarine { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aquamarine)); } }
		public static OutlineStyle Azure { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Azure)); } }
		public static OutlineStyle Beige { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Beige)); } }
		public static OutlineStyle Bisque { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Bisque)); } }
		public static OutlineStyle Black { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Black)); } }
		public static OutlineStyle BlanchedAlmond { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlanchedAlmond)); } }
		public static OutlineStyle Blue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Blue)); } }
		public static OutlineStyle BlueViolet { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlueViolet)); } }
		public static OutlineStyle Brown { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Brown)); } }
		public static OutlineStyle BurlyWood { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BurlyWood)); } }
		public static OutlineStyle CadetBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CadetBlue)); } }
		public static OutlineStyle Chartreuse { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chartreuse)); } }
		public static OutlineStyle Chocolate { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chocolate)); } }
		public static OutlineStyle Coral { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Coral)); } }
		public static OutlineStyle CornflowerBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CornflowerBlue)); } }
		public static OutlineStyle Cornsilk { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cornsilk)); } }
		public static OutlineStyle Crimson { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Crimson)); } }
		public static OutlineStyle Cyan { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cyan)); } }
		public static OutlineStyle DarkBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkBlue)); } }
		public static OutlineStyle DarkCyan { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkCyan)); } }
		public static OutlineStyle DarkGoldenrod { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGoldenrod)); } }
		public static OutlineStyle DarkGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGray)); } }
		public static OutlineStyle DarkGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGreen)); } }
		public static OutlineStyle DarkKhaki { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkKhaki)); } }
		public static OutlineStyle DarkMagenta { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkMagenta)); } }
		public static OutlineStyle DarkOliveGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOliveGreen)); } }
		public static OutlineStyle DarkOrange { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrange)); } }
		public static OutlineStyle DarkOrchid { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrchid)); } }
		public static OutlineStyle DarkRed { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkRed)); } }
		public static OutlineStyle DarkSalmon { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSalmon)); } }
		public static OutlineStyle DarkSeaGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSeaGreen)); } }
		public static OutlineStyle DarkSlateBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateBlue)); } }
		public static OutlineStyle DarkSlateGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateGray)); } }
		public static OutlineStyle DarkTurquoise { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkTurquoise)); } }
		public static OutlineStyle DarkViolet { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkViolet)); } }
		public static OutlineStyle DeepPink { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepPink)); } }
		public static OutlineStyle DeepSkyBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepSkyBlue)); } }
		public static OutlineStyle DimGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DimGray)); } }
		public static OutlineStyle DodgerBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DodgerBlue)); } }
		public static OutlineStyle Firebrick { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Firebrick)); } }
		public static OutlineStyle FloralWhite { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.FloralWhite)); } }
		public static OutlineStyle ForestGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ForestGreen)); } }
		public static OutlineStyle Fuchsia { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Fuchsia)); } }
		public static OutlineStyle Gainsboro { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gainsboro)); } }
		public static OutlineStyle GhostWhite { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GhostWhite)); } }
		public static OutlineStyle Gold { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gold)); } }
		public static OutlineStyle Goldenrod { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Goldenrod)); } }
		public static OutlineStyle Gray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gray)); } }
		public static OutlineStyle Green { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Green)); } }
		public static OutlineStyle GreenYellow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GreenYellow)); } }
		public static OutlineStyle Honeydew { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Honeydew)); } }
		public static OutlineStyle HotPink { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotPink)); } }
		public static OutlineStyle IndianRed { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.IndianRed)); } }
		public static OutlineStyle Indigo { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Indigo)); } }
		public static OutlineStyle Ivory { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Ivory)); } }
		public static OutlineStyle Khaki { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Khaki)); } }
		public static OutlineStyle Lavender { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lavender)); } }
		public static OutlineStyle LavenderBlush { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LavenderBlush)); } }
		public static OutlineStyle LawnGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LawnGreen)); } }
		public static OutlineStyle LemonChiffon { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LemonChiffon)); } }
		public static OutlineStyle LightBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightBlue)); } }
		public static OutlineStyle LightCoral { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCoral)); } }
		public static OutlineStyle LightCyan { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCyan)); } }
		public static OutlineStyle LightGoldenrodYellow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGoldenrodYellow)); } }
		public static OutlineStyle LightGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGray)); } }
		public static OutlineStyle LightGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGreen)); } }
		public static OutlineStyle LightPink { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightPink)); } }
		public static OutlineStyle LightSalmon { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSalmon)); } }
		public static OutlineStyle LightSeaGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSeaGreen)); } }
		public static OutlineStyle LightSkyBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSkyBlue)); } }
		public static OutlineStyle LightSlateGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSlateGray)); } }
		public static OutlineStyle LightSteelBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSteelBlue)); } }
		public static OutlineStyle LightYellow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightYellow)); } }
		public static OutlineStyle Lime { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lime)); } }
		public static OutlineStyle LimeGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LimeGreen)); } }
		public static OutlineStyle Linen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Linen)); } }
		public static OutlineStyle Magenta { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Magenta)); } }
		public static OutlineStyle Maroon { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Maroon)); } }
		public static OutlineStyle MediumAquamarine { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumAquamarine)); } }
		public static OutlineStyle MediumBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumBlue)); } }
		public static OutlineStyle MediumOrchid { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumOrchid)); } }
		public static OutlineStyle MediumPurple { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumPurple)); } }
		public static OutlineStyle MediumSeaGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSeaGreen)); } }
		public static OutlineStyle MediumSlateBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSlateBlue)); } }
		public static OutlineStyle MediumSpringGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSpringGreen)); } }
		public static OutlineStyle MediumTurquoise { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumTurquoise)); } }
		public static OutlineStyle MediumVioletRed { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumVioletRed)); } }
		public static OutlineStyle MidnightBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MidnightBlue)); } }
		public static OutlineStyle MintCream { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MintCream)); } }
		public static OutlineStyle MistyRose { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MistyRose)); } }
		public static OutlineStyle Moccasin { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Moccasin)); } }
		public static OutlineStyle NavajoWhite { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.NavajoWhite)); } }
		public static OutlineStyle Navy { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Navy)); } }
		public static OutlineStyle OldLace { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OldLace)); } }
		public static OutlineStyle Olive { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Olive)); } }
		public static OutlineStyle OliveDrab { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OliveDrab)); } }
		public static OutlineStyle Orange { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orange)); } }
		public static OutlineStyle OrangeRed { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OrangeRed)); } }
		public static OutlineStyle Orchid { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orchid)); } }
		public static OutlineStyle PaleGoldenrod { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGoldenrod)); } }
		public static OutlineStyle PaleGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGreen)); } }
		public static OutlineStyle PaleTurquoise { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleTurquoise)); } }
		public static OutlineStyle PaleVioletRed { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleVioletRed)); } }
		public static OutlineStyle PapayaWhip { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PapayaWhip)); } }
		public static OutlineStyle PeachPuff { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PeachPuff)); } }
		public static OutlineStyle Peru { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Peru)); } }
		public static OutlineStyle Pink { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Pink)); } }
		public static OutlineStyle Plum { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Plum)); } }
		public static OutlineStyle PowderBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PowderBlue)); } }
		public static OutlineStyle Purple { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Purple)); } }
		public static OutlineStyle Red { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Red)); } }
		public static OutlineStyle RosyBrown { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RosyBrown)); } }
		public static OutlineStyle RoyalBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RoyalBlue)); } }
		public static OutlineStyle SaddleBrown { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SaddleBrown)); } }
		public static OutlineStyle Salmon { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Salmon)); } }
		public static OutlineStyle SandyBrown { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SandyBrown)); } }
		public static OutlineStyle SeaGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaGreen)); } }
		public static OutlineStyle SeaShell { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaShell)); } }
		public static OutlineStyle Sienna { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Sienna)); } }
		public static OutlineStyle Silver { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Silver)); } }
		public static OutlineStyle SkyBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SkyBlue)); } }
		public static OutlineStyle SlateBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateBlue)); } }
		public static OutlineStyle SlateGray { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateGray)); } }
		public static OutlineStyle Snow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Snow)); } }
		public static OutlineStyle SpringGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SpringGreen)); } }
		public static OutlineStyle SteelBlue { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SteelBlue)); } }
		public static OutlineStyle Tan { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tan)); } }
		public static OutlineStyle Teal { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Teal)); } }
		public static OutlineStyle Thistle { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Thistle)); } }
		public static OutlineStyle Tomato { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tomato)); } }
		public static OutlineStyle Turquoise { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Turquoise)); } }
		public static OutlineStyle Violet { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Violet)); } }
		public static OutlineStyle Wheat { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Wheat)); } }
		public static OutlineStyle White { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.White)); } }
		public static OutlineStyle WhiteSmoke { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WhiteSmoke)); } }
		public static OutlineStyle Yellow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Yellow)); } }
		public static OutlineStyle YellowGreen { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.YellowGreen)); } }
		public static OutlineStyle ButtonFace { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonFace)); } }
		public static OutlineStyle ButtonHighlight { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonHighlight)); } }
		public static OutlineStyle ButtonShadow { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonShadow)); } }
		public static OutlineStyle GradientActiveCaption { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientActiveCaption)); } }
		public static OutlineStyle GradientInactiveCaption { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientInactiveCaption)); } }
		public static OutlineStyle MenuBar { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuBar)); } }
		public static OutlineStyle MenuHighlight { get { return new OutlineStyle(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuHighlight)); } }
	}
}