namespace SimpleCAD
{
    public partial struct Style
    {
		public static Style ActiveBorder { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveBorder)); } }
		public static Style ActiveCaption { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaption)); } }
		public static Style ActiveCaptionText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ActiveCaptionText)); } }
		public static Style AppWorkspace { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AppWorkspace)); } }
		public static Style Control { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Control)); } }
		public static Style ControlDark { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDark)); } }
		public static Style ControlDarkDark { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlDarkDark)); } }
		public static Style ControlLight { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLight)); } }
		public static Style ControlLightLight { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlLightLight)); } }
		public static Style ControlText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ControlText)); } }
		public static Style Desktop { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Desktop)); } }
		public static Style GrayText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GrayText)); } }
		public static Style Highlight { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Highlight)); } }
		public static Style HighlightText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HighlightText)); } }
		public static Style HotTrack { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotTrack)); } }
		public static Style InactiveBorder { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveBorder)); } }
		public static Style InactiveCaption { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaption)); } }
		public static Style InactiveCaptionText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InactiveCaptionText)); } }
		public static Style Info { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Info)); } }
		public static Style InfoText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.InfoText)); } }
		public static Style Menu { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Menu)); } }
		public static Style MenuText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuText)); } }
		public static Style ScrollBar { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ScrollBar)); } }
		public static Style Window { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Window)); } }
		public static Style WindowFrame { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowFrame)); } }
		public static Style WindowText { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WindowText)); } }
		public static Style Transparent { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Transparent)); } }
		public static Style AliceBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AliceBlue)); } }
		public static Style AntiqueWhite { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.AntiqueWhite)); } }
		public static Style Aqua { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aqua)); } }
		public static Style Aquamarine { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Aquamarine)); } }
		public static Style Azure { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Azure)); } }
		public static Style Beige { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Beige)); } }
		public static Style Bisque { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Bisque)); } }
		public static Style Black { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Black)); } }
		public static Style BlanchedAlmond { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlanchedAlmond)); } }
		public static Style Blue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Blue)); } }
		public static Style BlueViolet { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BlueViolet)); } }
		public static Style Brown { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Brown)); } }
		public static Style BurlyWood { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.BurlyWood)); } }
		public static Style CadetBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CadetBlue)); } }
		public static Style Chartreuse { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chartreuse)); } }
		public static Style Chocolate { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Chocolate)); } }
		public static Style Coral { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Coral)); } }
		public static Style CornflowerBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.CornflowerBlue)); } }
		public static Style Cornsilk { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cornsilk)); } }
		public static Style Crimson { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Crimson)); } }
		public static Style Cyan { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Cyan)); } }
		public static Style DarkBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkBlue)); } }
		public static Style DarkCyan { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkCyan)); } }
		public static Style DarkGoldenrod { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGoldenrod)); } }
		public static Style DarkGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGray)); } }
		public static Style DarkGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkGreen)); } }
		public static Style DarkKhaki { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkKhaki)); } }
		public static Style DarkMagenta { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkMagenta)); } }
		public static Style DarkOliveGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOliveGreen)); } }
		public static Style DarkOrange { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrange)); } }
		public static Style DarkOrchid { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkOrchid)); } }
		public static Style DarkRed { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkRed)); } }
		public static Style DarkSalmon { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSalmon)); } }
		public static Style DarkSeaGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSeaGreen)); } }
		public static Style DarkSlateBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateBlue)); } }
		public static Style DarkSlateGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkSlateGray)); } }
		public static Style DarkTurquoise { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkTurquoise)); } }
		public static Style DarkViolet { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DarkViolet)); } }
		public static Style DeepPink { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepPink)); } }
		public static Style DeepSkyBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DeepSkyBlue)); } }
		public static Style DimGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DimGray)); } }
		public static Style DodgerBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.DodgerBlue)); } }
		public static Style Firebrick { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Firebrick)); } }
		public static Style FloralWhite { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.FloralWhite)); } }
		public static Style ForestGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ForestGreen)); } }
		public static Style Fuchsia { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Fuchsia)); } }
		public static Style Gainsboro { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gainsboro)); } }
		public static Style GhostWhite { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GhostWhite)); } }
		public static Style Gold { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gold)); } }
		public static Style Goldenrod { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Goldenrod)); } }
		public static Style Gray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Gray)); } }
		public static Style Green { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Green)); } }
		public static Style GreenYellow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GreenYellow)); } }
		public static Style Honeydew { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Honeydew)); } }
		public static Style HotPink { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.HotPink)); } }
		public static Style IndianRed { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.IndianRed)); } }
		public static Style Indigo { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Indigo)); } }
		public static Style Ivory { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Ivory)); } }
		public static Style Khaki { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Khaki)); } }
		public static Style Lavender { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lavender)); } }
		public static Style LavenderBlush { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LavenderBlush)); } }
		public static Style LawnGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LawnGreen)); } }
		public static Style LemonChiffon { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LemonChiffon)); } }
		public static Style LightBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightBlue)); } }
		public static Style LightCoral { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCoral)); } }
		public static Style LightCyan { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightCyan)); } }
		public static Style LightGoldenrodYellow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGoldenrodYellow)); } }
		public static Style LightGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGray)); } }
		public static Style LightGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightGreen)); } }
		public static Style LightPink { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightPink)); } }
		public static Style LightSalmon { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSalmon)); } }
		public static Style LightSeaGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSeaGreen)); } }
		public static Style LightSkyBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSkyBlue)); } }
		public static Style LightSlateGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSlateGray)); } }
		public static Style LightSteelBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightSteelBlue)); } }
		public static Style LightYellow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LightYellow)); } }
		public static Style Lime { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Lime)); } }
		public static Style LimeGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.LimeGreen)); } }
		public static Style Linen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Linen)); } }
		public static Style Magenta { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Magenta)); } }
		public static Style Maroon { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Maroon)); } }
		public static Style MediumAquamarine { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumAquamarine)); } }
		public static Style MediumBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumBlue)); } }
		public static Style MediumOrchid { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumOrchid)); } }
		public static Style MediumPurple { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumPurple)); } }
		public static Style MediumSeaGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSeaGreen)); } }
		public static Style MediumSlateBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSlateBlue)); } }
		public static Style MediumSpringGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumSpringGreen)); } }
		public static Style MediumTurquoise { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumTurquoise)); } }
		public static Style MediumVioletRed { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MediumVioletRed)); } }
		public static Style MidnightBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MidnightBlue)); } }
		public static Style MintCream { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MintCream)); } }
		public static Style MistyRose { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MistyRose)); } }
		public static Style Moccasin { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Moccasin)); } }
		public static Style NavajoWhite { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.NavajoWhite)); } }
		public static Style Navy { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Navy)); } }
		public static Style OldLace { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OldLace)); } }
		public static Style Olive { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Olive)); } }
		public static Style OliveDrab { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OliveDrab)); } }
		public static Style Orange { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orange)); } }
		public static Style OrangeRed { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.OrangeRed)); } }
		public static Style Orchid { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Orchid)); } }
		public static Style PaleGoldenrod { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGoldenrod)); } }
		public static Style PaleGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleGreen)); } }
		public static Style PaleTurquoise { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleTurquoise)); } }
		public static Style PaleVioletRed { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PaleVioletRed)); } }
		public static Style PapayaWhip { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PapayaWhip)); } }
		public static Style PeachPuff { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PeachPuff)); } }
		public static Style Peru { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Peru)); } }
		public static Style Pink { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Pink)); } }
		public static Style Plum { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Plum)); } }
		public static Style PowderBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.PowderBlue)); } }
		public static Style Purple { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Purple)); } }
		public static Style Red { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Red)); } }
		public static Style RosyBrown { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RosyBrown)); } }
		public static Style RoyalBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.RoyalBlue)); } }
		public static Style SaddleBrown { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SaddleBrown)); } }
		public static Style Salmon { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Salmon)); } }
		public static Style SandyBrown { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SandyBrown)); } }
		public static Style SeaGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaGreen)); } }
		public static Style SeaShell { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SeaShell)); } }
		public static Style Sienna { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Sienna)); } }
		public static Style Silver { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Silver)); } }
		public static Style SkyBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SkyBlue)); } }
		public static Style SlateBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateBlue)); } }
		public static Style SlateGray { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SlateGray)); } }
		public static Style Snow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Snow)); } }
		public static Style SpringGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SpringGreen)); } }
		public static Style SteelBlue { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.SteelBlue)); } }
		public static Style Tan { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tan)); } }
		public static Style Teal { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Teal)); } }
		public static Style Thistle { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Thistle)); } }
		public static Style Tomato { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Tomato)); } }
		public static Style Turquoise { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Turquoise)); } }
		public static Style Violet { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Violet)); } }
		public static Style Wheat { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Wheat)); } }
		public static Style White { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.White)); } }
		public static Style WhiteSmoke { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.WhiteSmoke)); } }
		public static Style Yellow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.Yellow)); } }
		public static Style YellowGreen { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.YellowGreen)); } }
		public static Style ButtonFace { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonFace)); } }
		public static Style ButtonHighlight { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonHighlight)); } }
		public static Style ButtonShadow { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.ButtonShadow)); } }
		public static Style GradientActiveCaption { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientActiveCaption)); } }
		public static Style GradientInactiveCaption { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.GradientInactiveCaption)); } }
		public static Style MenuBar { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuBar)); } }
		public static Style MenuHighlight { get { return new Style(System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor.MenuHighlight)); } }
	}
}